let allMusic = [
    {
    name: "Xcho & Mr Lambo & Пабло - Дай Мне Огня",
    artist: "Xcho & Mr Lambo & Пабло",
    src: "music-1",
    img: "music-icon",
},
    {
    name: "Егор Крид - Pussy Boy",
    artist: "Егор Крид",
    src: "music-2",
    img: "music-icon",
},
    {
    name: "Orheyn - Karacadag",
    artist: "Orheyn",
    src: "music-3",
    img: "music-icon",
},
    {
    name: "MASSA Feat. ABBBOSE - Mahalla",
    artist: "MASSA Feat. ABBBOSE",
    src: "music-4",
    img: "music-icon",
},
    {
    name: "Nijat Masimov - Faridam",
    artist: "Nijat Masimov",
    src: "music-5",
    img: "music-icon",
},
    {
    name: "Dior Production - Gozalim asalim",
    artist: "Dior Production",
    src: "music-6",
    img: "music-icon",
},
    {
    name: "Jnathyn-Dioma - SoundCloud",
    artist: "Jnathyn-Dioma",
    src: "music-7",
    img: "music-icon",
},
    {
    name: "Green71 - Yarashadi sanga",
    artist: "Green71",
    src: "music-8",
    img: "music-icon",
},
    {
    name: "Green71 - Bu mani uyim",
    artist: "Green71",
    src: "music-9",
    img: "music-icon",
},
    {
    name: "Green71 - Sevgi bu armon 2",
    artist: "Green71",
    src: "music-10",
    img: "music-icon",
},
    {
    name: "Green71 - Yolgizlikda yaxshi",
    artist: "Green71",
    src: "music-11",
    img: "music-icon",
},
    {
    name: "Gio Pika - Buyno golova",
    artist: "Gio Pika",
    src: "music-12",
    img: "music-icon",
},
    {
    name: "Vakhid ft. Sakhievvv ft. Yorka - AKKURATNIY BOLA",
    artist: "Vakhid ft. Sakhievvv ft. Yorka",
    src: "music-13",
    img: "music-icon",
},
    {
    name: "Edmofo and Camelia Jordana - Doudou",
    artist: "Edmofo and Camelia Jordana",
    src: "music-14",
    img: "music-icon",
},
    {
    name: "Jah Khalib - Leyla 8D",
    artist: "Jah Khalib",
    src: "music-15",
    img: "music-icon",
},
    {
    name: "Jah Khalib - Искал Нашёл 8D  🎧",
    artist: "Jah Khalib",
    src: "music-16",
    img: "music-icon",
},
    {
    name: "N3WPORT, Meggie York - Runaway",
    artist: "N3WPORT, Meggie York",
    src: "music-17",
    img: "music-icon",
},
    {
    name: "SHOOVAL - Мы открываем бизнес",
    artist: "SHOOVAL",
    src: "music-18",
    img: "music-icon",
},
    {
    name: "XXTENTACTION - She said I oh I am fall",
    artist: "XXTENTACTION",
    src: "music-19",
    img: "music-icon",
},
    {
    name: "Boywithuke - Toxic Remix",
    artist: "Boywithuke",
    src: "music-20",
    img: "music-icon",
},
    {
    name: "Asanrap - Шома Тигр",
    artist: "Asanrap",
    src: "music-21",
    img: "music-icon",
},
    {
    name: "Uzboom G-Said - Tugilgan Kun Muborak",
    artist: "Uzboom G-Said",
    src: "music-22",
    img: "music-icon",
},
    {
    name: "G-said - Yaxshi Bollaga",
    artist: "G-Said",
    src: "music-23",
    img: "music-icon",
},
    {
    name: "Green71 Sardor Safarov - Yomgir 2",
    artist: "Green71 Sardor Safarov",
    src: "music-24",
    img: "music-icon",
},
    {
    name: "Facading - You and Me",
    artist: "Facading",
    src: "music-25",
    img: "music-icon",
},
    {
    name: "Бока - Dolya Vorovskaya",
    artist: "Бока",
    src: "music-26",
    img: "music-icon",
},
    {
    name: "Hammali Navai Jah Khalib - Боже как завидую",
    artist: "Hammali Navai Jah Khalib",
    src: "music-27",
    img: "music-icon",
},
    {
    name: "Gio Pika - Buyno Golova",
    artist: "Gio Pika",
    src: "music-28",
    img: "music-icon",
},
    {
    name: "RAIKAHO Soul - Из чёрного мерина",
    artist: "RAIKAHO Soul",
    src: "music-29",
    img: "music-icon",
},
    {
    name: "Ислам Нашидов - Нашид Ин арадтум",
    artist: "Ислам Нашидов",
    src: "music-30",
    img: "music-icon",
},
    {
    name: "Jah Khalib - Лиловая",
    artist: "Jah Khalib",
    src: "music-31",
    img: "music-icon",
},
    {
    name: "Matrang - Медуза",
    artist: "Matrang",
    src: "music-32",
    img: "music-icon",
},
    {
    name: "DONI Полина Терехова - Мотив",
    artist: "DONI Полина Терехова",
    src: "music-33",
    img: "music-icon",
},
    {
    name: "Miyagi & Andy Panda - Патрон",
    artist: "Miyagi & Andy Panda",
    src: "music-34",
    img: "music-icon",
},
    {
    name: "Timur Alixonov - Такой лёгкий",
    artist: "Timur Alixonov",
    src: "music-35",
    img: "music-icon",
},
];